#!/usr/bin/env python3
"""SPOOL host-helper — Windows edition. Same role as host_helper.py (the
one piece of SPOOL that isn't Docker), just for a Windows host instead of
a Mac one: a Linux container can't launch a native GUI app either way, so
this runs directly on Windows and starts automatically at login (see
install_windows.ps1 — a Startup-folder VBS launcher, the closest Windows
equivalent to launchd). Listens on loopback only; the `api` container
reaches it via Docker Desktop's `host.docker.internal` DNS name, which
routes to loopback-bound host services exactly as it does on Mac.

Deliberately stdlib-only (http.server + subprocess), matching
host_helper.py — this is a one-route job, and a framework would just mean
a venv to create and keep in sync on the host, which is exactly the
operational overhead a simple background script should avoid.

Protocol-compatible with host_helper.py — identical JSON request/response
shapes on the same two routes, so services/api/spool_api/host_helper_client.py
(which the `api` container actually talks to) needs no changes regardless
of which OS is on the other end of the request.

Watched-root paths (DROPFOLDER_HOST_PATH etc., and everything in the
`files.path` column) are expected to use forward slashes even on Windows
("C:/Users/you/Library", not "C:\\Users\\you\\Library") — this is the one
convention that lets the Linux-container-side code (common/paths.py) treat
a Windows host path as an ordinary POSIX-style string with no special
casing, and Windows itself accepts forward slashes everywhere that matters
here (os.path, subprocess, os.startfile) just as readily as backslashes.
"""
import json
import os
import subprocess
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HOST = "127.0.0.1"
PORT = 8100

# ext -> a friendly app label (matches services/api/spool_api/
# host_helper_client.py's APP_MAP exactly — that's what the `api` container
# actually sends as `app` in the /open request body). Windows has no
# bundle-name-to-launch-command resolution the way macOS's `open -a` does,
# so a second table (APP_PATHS, below) maps each label to the real, full
# path of its .exe on this specific machine. Auto-populated by
# `host-helper/configure_apps.py` (run by setup.ps1, or standalone) —
# edit by hand instead if you'd rather, just re-run install_windows.ps1
# afterwards either way.
# APP_MAP:BEGIN (auto-generated by host-helper/configure_apps.py — edit here directly, or just re-run that script)
APP_MAP = {
    ".step": "Autodesk Fusion",
    ".stp": "Autodesk Fusion",
    ".f3d": "Autodesk Fusion",
    ".scad": "Autodesk Fusion",
    ".stl": "BambuStudio",
    ".3mf": "BambuStudio",
    ".svg": "BambuStudio",
    ".gcode": "BambuStudio",
    ".obj": "BambuStudio",
}
# APP_MAP:END

# label -> full path to the real installed .exe on this machine — highly
# machine-specific (unlike a macOS bundle name, an .exe path isn't
# portable between two Windows installs even for the exact same app), so
# unlike APP_MAP this table is never shared with host_helper_client.py.
# APP_PATHS:BEGIN (auto-generated by host-helper/configure_apps.py — edit here directly, or just re-run that script)
APP_PATHS = {
    "Autodesk Fusion": "C:/Program Files/Autodesk/webdeploy/production/Autodesk Fusion.exe",
    "BambuStudio": "C:/Program Files/Bambu Studio/bambu-studio.exe",
}
# APP_PATHS:END
ALLOWED_APPS = set(APP_MAP.values())

# Real deletion requires real OS-level filesystem access, which is exactly
# what the api/worker containers don't reliably have (Library is mounted
# :ro in Docker regardless of the real OS permissions) — host-helper runs
# natively, so it can. Deletion is irreversible, so — unlike /open, which
# only ever launches a GUI app — this endpoint independently re-validates
# that the path falls under a known watched root rather than trusting the
# caller entirely, even though the api container only ever sources paths
# from real `files.path` DB rows. Read from the same env vars docker-compose
# uses for the watched-root bind mounts (see .env.example), injected by
# install_windows.ps1's generated launcher, rather than hardcoded to one
# machine's paths — if none are set, the list is empty and every delete is
# rejected, which is the safe direction to fail in. Unlike the macOS
# host-helper, there's no separate OS-level permission grant needed here
# beyond the normal file permissions Windows already applies to your own
# user account — os.remove just works.
ALLOWED_DELETE_ROOTS = [
    p
    for p in (
        os.environ.get("DROPFOLDER_HOST_PATH"),
        os.environ.get("LIBRARY_HOST_PATH"),
        os.environ.get("DOWNLOADS_HOST_PATH"),
    )
    if p
]


def _under_allowed_root(path):
    return any(os.path.commonpath([path, root]) == root for root in ALLOWED_DELETE_ROOTS)


class Handler(BaseHTTPRequestHandler):
    def _send(self, status, body):
        payload = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def _read_json(self):
        length = int(self.headers.get("Content-Length", 0))
        return json.loads(self.rfile.read(length))

    def do_POST(self):
        if self.path == "/open":
            self._handle_open()
        elif self.path == "/delete":
            self._handle_delete()
        else:
            self._send(404, {"error": "not found"})

    def _handle_open(self):
        try:
            data = self._read_json()
        except json.JSONDecodeError:
            self._send(400, {"error": "invalid json"})
            return

        path = data.get("path")
        app = data.get("app")

        if not path or not os.path.isfile(path):
            self._send(404, {"error": "file not found on disk"})
            return

        if app:
            # Never trust the caller's app name into subprocess, even though
            # subprocess.run's list form isn't shell-injectable — constrain
            # to known installed apps regardless of what the api container
            # sends, same as host_helper.py.
            if app not in ALLOWED_APPS:
                self._send(400, {"error": f"app not allowed: {app}"})
                return
            exe_path = APP_PATHS.get(app)
            if not exe_path or not os.path.isfile(exe_path):
                self._send(500, {"error": f"configured app {app!r} not found at its configured path — re-run configure_apps.py"})
                return
            command = [exe_path, path]
            try:
                subprocess.run(command, check=True)
            except subprocess.CalledProcessError as exc:
                self._send(500, {"error": str(exc)})
                return
        else:
            # No app specified — hand off to Windows' own registered
            # default handler (used for sidecar files like README/PDF/
            # preview images, which aren't in APP_MAP since they're not
            # CAD files with one obvious app to open them in). os.startfile
            # is the direct stdlib equivalent of macOS's `open path` — no
            # subprocess needed at all.
            try:
                os.startfile(path)  # noqa: only exists on Windows, by design
            except OSError as exc:
                self._send(500, {"error": str(exc)})
                return

        self._send(200, {"status": "ok"})

    def _handle_delete(self):
        try:
            data = self._read_json()
        except json.JSONDecodeError:
            self._send(400, {"error": "invalid json"})
            return

        path = data.get("path")

        if not path or not os.path.isfile(path):
            self._send(404, {"error": "file not found on disk"})
            return

        if not _under_allowed_root(path):
            self._send(400, {"error": "path is outside known watched roots"})
            return

        try:
            os.remove(path)
        except OSError as exc:
            self._send(500, {"error": str(exc)})
            return

        self._send(200, {"status": "ok"})


def main():
    if not ALLOWED_DELETE_ROOTS:
        print(
            "[host-helper] WARNING: no ALLOWED_DELETE_ROOTS configured "
            "(DROPFOLDER_HOST_PATH/LIBRARY_HOST_PATH/DOWNLOADS_HOST_PATH not "
            "set) — every /delete request will be rejected. Re-run "
            "install_windows.ps1 after setting these in .env.",
            flush=True,
        )
    server = ThreadingHTTPServer((HOST, PORT), Handler)
    print(f"[host-helper] listening on {HOST}:{PORT}", flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
