import base64
import textwrap

from app.gcode_thumbnail import extract_gcode_thumbnail


def _thumbnail_block(width, height, raw_bytes):
    encoded = base64.b64encode(raw_bytes).decode("ascii")
    lines = textwrap.wrap(encoded, 78)
    body = "\n".join(f"; {line}" for line in lines)
    return f"; thumbnail begin {width}x{height} {len(raw_bytes)}\n{body}\n; thumbnail end\n"


def _write_gcode(path, content):
    path.write_text(content)
    return str(path)


def test_extract_gcode_thumbnail_returns_none_when_absent(tmp_path):
    gcode = _write_gcode(
        tmp_path / "no-thumb.gcode",
        "; generated by PrusaSlicer 2.6.1\n; thumbnails = \nG28\nG1 X10 Y10\n",
    )
    assert extract_gcode_thumbnail(gcode, file_id=1) is None


def test_extract_gcode_thumbnail_extracts_embedded_png(tmp_path, monkeypatch):
    import app.gcode_thumbnail as gcode_thumbnail

    monkeypatch.setattr(gcode_thumbnail, "THUMBNAILS_DIR", str(tmp_path / "thumbs"))

    raw_bytes = bytes(range(256)) * 3  # arbitrary but deterministic payload
    content = (
        "; generated by PrusaSlicer 2.6.1\n"
        + _thumbnail_block(32, 32, raw_bytes)
        + "\nG28\nG1 X10 Y10\n"
    )
    gcode = _write_gcode(tmp_path / "with-thumb.gcode", content)

    filename = extract_gcode_thumbnail(gcode, file_id=42)
    assert filename == "42.png"
    saved = (tmp_path / "thumbs" / filename).read_bytes()
    assert saved == raw_bytes


def test_extract_gcode_thumbnail_picks_the_largest_of_several(tmp_path, monkeypatch):
    import app.gcode_thumbnail as gcode_thumbnail

    monkeypatch.setattr(gcode_thumbnail, "THUMBNAILS_DIR", str(tmp_path / "thumbs"))

    small = b"small-thumbnail-payload"
    large = b"large-thumbnail-payload-with-more-bytes-in-it"
    content = (
        "; generated by SuperSlicer\n"
        + _thumbnail_block(16, 16, small)
        + "\n"
        + _thumbnail_block(300, 300, large)
        + "\nG28\n"
    )
    gcode = _write_gcode(tmp_path / "multi-thumb.gcode", content)

    filename = extract_gcode_thumbnail(gcode, file_id=7)
    saved = (tmp_path / "thumbs" / filename).read_bytes()
    assert saved == large
