from app.gcode_metadata import extract_gcode_metadata

_REAL_STYLE_GCODE = """; generated by PrusaSlicer 2.6.1+win64 on 2023-10-07 at 07:16:36 UTC
;
G28 ; home all
G1 X10 Y10 E1
M84 ; disable motors
; filament used [mm] = 79653.73
; filament used [cm3] = 191.59
; filament used [g] = 243.32
; total filament used [g] = 243.32
; total filament cost = 8.83
; estimated printing time (normal mode) = 9h 8m 25s
; estimated printing time (silent mode) = 9h 11m 56s

; prusaslicer_config = begin
; filament_settings_id = "Prusament PETG"
; filament_type = PETG
; fill_density = 20%
; layer_height = 0.3
; nozzle_diameter = 0.4
; print_settings_id = 0.30mm DRAFT @MK3
; printer_model = MK3S
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; prusaslicer_config = end
"""


def _write(path, content):
    path.write_text(content)
    return str(path)


def test_extract_gcode_metadata_from_real_style_footer(tmp_path):
    gcode = _write(tmp_path / "real-style.gcode", _REAL_STYLE_GCODE)
    metadata = extract_gcode_metadata(gcode)

    assert metadata is not None
    assert metadata["material"] == "PETG"
    assert metadata["printer_profile"] == "MK3S"
    assert metadata["slicer"] == "PrusaSlicer 2.6.1+win64"
    settings = metadata["settings_json"]
    assert settings["nozzle_diameter_mm"] == 0.4
    assert settings["layer_height_mm"] == 0.3
    assert settings["infill_density_pct"] == 20.0
    assert settings["filament_types"] == ["PETG"]
    assert settings["filament_used_g"] == 243.32
    assert settings["estimated_print_time_min"] == 548.4
    assert settings["printer_model"] == "MK3S"


def test_extract_gcode_metadata_returns_none_without_recognized_footer(tmp_path):
    gcode = _write(tmp_path / "no-footer.gcode", "; a plain hand-written gcode\nG28\nG1 X10 Y10\n")
    assert extract_gcode_metadata(gcode) is None


def test_extract_gcode_metadata_prefers_total_filament_used(tmp_path):
    # A multi-object print's per-segment "filament used [g]" can differ
    # from the "total filament used [g]" summed across the whole plate —
    # the total is the one that actually matters.
    content = _REAL_STYLE_GCODE.replace(
        "; total filament used [g] = 243.32", "; total filament used [g] = 500.0"
    )
    gcode = _write(tmp_path / "totals.gcode", content)
    metadata = extract_gcode_metadata(gcode)
    assert metadata["settings_json"]["filament_used_g"] == 500.0
