"""Extracts print settings from a gcode file's own header/footer —
PrusaSlicer/SuperSlicer/OrcaSlicer (a shared lineage, hence the same
config key names) write a `; generated by <Slicer> <version> ...` line
as the very first line, then a full profile dump as `; key = value`
comment lines in the footer (after the print body, following a loose
filament-used/print-time summary block with no begin/end markers of its
own, then `; <slicer>_config = begin` ... `; <slicer>_config = end`).
Both the summary and the profile dump are the same `; key = value`
shape, just from two different sources within the footer — parsed
together here rather than delineating them separately, since all we
actually want is a handful of specific named keys regardless of which
part they came from.

Verified against real PrusaSlicer-exported gcode already in this
library. Bambu Studio's own gcode export has NOT been verified against
a real sample (none in this library — Bambu's own workflow exports
`.3mf` project files, not plain sliced gcode, as far as this library's
real content shows) — if its footer uses different key names, this
simply returns None rather than guessing, same as any gcode with no
recognizable slicer footer at all.

Deliberately its own lightweight module (stdlib only), matching
gcode_thumbnail.py/bambu_metadata.py's precedent — nothing here needs
pyrender/trimesh.
"""
import os
import re

# The metadata footer always follows the (potentially huge, tens-of-MB)
# print body — reading from the end is far cheaper than scanning from
# the start, same reasoning as gcode_thumbnail.py scanning only the head.
_TAIL_SCAN_BYTES = 300_000
_HEAD_SCAN_BYTES = 4_096

_SETTING_LINE_RE = re.compile(r"^;\s*([^=]+?)\s*=\s*(.*)$")
_GENERATED_BY_RE = re.compile(r"^;\s*generated by\s+(\S+)\s+(\S+)", re.IGNORECASE)


def _read_text(container_path, offset, size):
    with open(container_path, "rb") as f:
        f.seek(offset)
        return f.read(size).decode("utf-8", errors="ignore")


def _parse_comment_settings(text):
    """Every `; key = value` comment line, keyed by the exact key text as
    written — summary keys like "filament used [g]" and profile-dump
    keys like "nozzle_diameter" end up in the same dict; callers just
    look up the specific ones they want."""
    settings = {}
    for line in text.splitlines():
        m = _SETTING_LINE_RE.match(line.strip())
        if not m:
            continue
        key, value = m.group(1).strip(), m.group(2).strip()
        settings[key] = value.strip('"')
    return settings


def _parse_float(raw):
    if raw is None:
        return None
    match = re.search(r"[\d.]+", raw)
    return float(match.group()) if match else None


def _parse_duration_minutes(raw):
    """'9h 8m 25s' -> 548.4 — same unit (minutes) bambu_metadata.py's
    estimated_print_time_min already uses."""
    if raw is None:
        return None
    hours = re.search(r"(\d+)h", raw)
    minutes = re.search(r"(\d+)m", raw)
    seconds = re.search(r"(\d+)s", raw)
    if not (hours or minutes or seconds):
        return None
    total = 0.0
    if hours:
        total += int(hours.group(1)) * 60
    if minutes:
        total += int(minutes.group(1))
    if seconds:
        total += int(seconds.group(1)) / 60
    return round(total, 1)


def extract_gcode_metadata(container_path):
    """Returns a dict shaped like bambu_metadata.extract_bambu_metadata's
    return value, or None if this gcode's footer doesn't look like a
    recognized slicer config dump at all."""
    size = os.path.getsize(container_path)
    tail_text = _read_text(container_path, max(0, size - _TAIL_SCAN_BYTES), _TAIL_SCAN_BYTES)
    settings = _parse_comment_settings(tail_text)

    # Every recognized slicer's config dump writes at least one of these
    # — their absence means this footer isn't a slicer config dump at
    # all (a hand-authored or stripped-down gcode), not just a couple of
    # fields being unset.
    if "nozzle_diameter" not in settings and "printer_model" not in settings:
        return None

    head_text = _read_text(container_path, 0, _HEAD_SCAN_BYTES)
    slicer = None
    for line in head_text.splitlines():
        m = _GENERATED_BY_RE.match(line.strip())
        if m:
            slicer = f"{m.group(1)} {m.group(2)}"
            break

    filament_type = settings.get("filament_type")
    printer_model = settings.get("printer_model")
    filament_used_g = _parse_float(settings.get("total filament used [g]") or settings.get("filament used [g]"))

    return {
        "material": filament_type,
        "printer_profile": printer_model,
        "slicer": slicer,
        "settings_json": {
            "nozzle_diameter_mm": _parse_float(settings.get("nozzle_diameter")),
            "layer_height_mm": _parse_float(settings.get("layer_height")),
            "infill_density_pct": _parse_float(settings.get("fill_density")),
            "filament_types": [filament_type] if filament_type else [],
            "filament_used_g": filament_used_g,
            "estimated_print_time_min": _parse_duration_minutes(
                settings.get("estimated printing time (normal mode)")
            ),
            "printer_model": printer_model,
        },
    }
